"""add employer profile extended fields

Revision ID: 2175efeaba6e
Revises: 63edca3bfb16
Create Date: 2026-02-26 18:15:58.010518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2175efeaba6e'
down_revision: Union[str, Sequence[str], None] = '63edca3bfb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_edit_approval_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('requester_user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_edit_approval_tokens_job_id'), 'job_edit_approval_tokens', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_edit_approval_tokens_owner_user_id'), 'job_edit_approval_tokens', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_job_edit_approval_tokens_requester_user_id'), 'job_edit_approval_tokens', ['requester_user_id'], unique=False)
    op.add_column('employer_profiles', sa.Column('cover_image_url', sa.String(length=1024), nullable=True))
    op.add_column('employer_profiles', sa.Column('headquarters', sa.String(length=255), nullable=True))
    op.add_column('employer_profiles', sa.Column('employees_count', sa.Integer(), nullable=True))
    op.add_column('employer_profiles', sa.Column('founded_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employer_profiles', 'founded_year')
    op.drop_column('employer_profiles', 'employees_count')
    op.drop_column('employer_profiles', 'headquarters')
    op.drop_column('employer_profiles', 'cover_image_url')
    op.drop_index(op.f('ix_job_edit_approval_tokens_requester_user_id'), table_name='job_edit_approval_tokens')
    op.drop_index(op.f('ix_job_edit_approval_tokens_owner_user_id'), table_name='job_edit_approval_tokens')
    op.drop_index(op.f('ix_job_edit_approval_tokens_job_id'), table_name='job_edit_approval_tokens')
    op.drop_table('job_edit_approval_tokens')
    # ### end Alembic commands ###
