"""add employer profile extended fields

Revision ID: c206d7499905
Revises: 2175efeaba6e
Create Date: 2026-02-26 18:33:57.232600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c206d7499905'
down_revision: Union[str, Sequence[str], None] = '2175efeaba6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('what_to_expect', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('additional_benefits', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('openings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'openings')
    op.drop_column('jobs', 'additional_benefits')
    op.drop_column('jobs', 'what_to_expect')
    op.drop_column('jobs', 'requirements')
    # ### end Alembic commands ###
